server:
  port: 10010

spring:
  application:
    name: gateway-server #serviceName
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:9101
          predicates:
            #- Path=/user/**,/role/**
            #- RbacAuth=rbac
            - name: RbacAuth
              args:
                flag: rbac

