server:
  port: 9002

spring:
  application:
    name: seatashop-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://senvmc1a:3306/seata_shop_order?
      serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: APJ@com123
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 785fa1c8-0f7a-4cca-9321-4cbc30914af5
        cluster-name: BJ

seatashop-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients:
      - seatashop-user

# MyBatisPlus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
  type-aliases-package: org.seatashop.shop.pojo

logging:
  level:
    org.seatashop.shop: debug

#feign:
#  client:
#    config:
#      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
#        loggerLevel: FULL # 日志级别

# eureka client
#eureka:
#  client:
#    service-url:
#      defaultZone: http://seatashop:seatashop123@localhost:8761/eureka/eureka
