server:
  port: 10010
spring:
  application:
    name: gateway-server #serviceName

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.133:7801
    gateway:
      # 全局的跨域处理
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':   # 哪些访问地址做跨域处理
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000  # 这次跨域检测的有效期
      # 路由配置
      routes:
        - id: user  # 唯一ID
          #uri: http://localhost:9101   # 路由转发的路径
          uri: lb://mafeng-user  # mafeng-user在Nacos注册的serviceName  lb:// 底层就是采用Ribbon实现负载均衡
          predicates:  # 断言（匹配规则）
            - Path=/api/user/**
            #- Query=name,jack
            #- RbacAuth=rbac
            #- name: RbacAuth
            #  args:
            #    flag: rbac
            #    name: user
          filters:
            - AddRequestHeader=Authorization, jack
            - AddRequestParameter=name, lucy
            - StripPrefix=2  # 截断了Path路径的前两个路径
            #- IPForbid=192.168.0.104
            - name: IPForbid
              args:
                permitIP: 192.168.0.104

