version: '3.1'
services:
      zoo1:
          image: zookeeper:3.5.7
          restart: always
          container_name: zoo1
          ports:
            - 2181:2181
          volumes:
            - /home/zk/zoo1/data:/data
            - /home/zk/zoo1/datalog:/datalog
          environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
            ZOO_AUTOPURGE_PURGEINTERVAL: 1

      zoo2:
          image: zookeeper:3.5.7
          restart: always
          container_name: zoo2
          ports:
            - 2182:2181
          volumes:
            - /home/zk/zoo2/data:/data
            - /home/zk/zoo2/datalog:/datalog
          environment:
             ZOO_MY_ID: 2
             ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
             ZOO_AUTOPURGE_PURGEINTERVAL: 1

      zoo3:
          image: zookeeper:3.5.7
          restart: always
          container_name: zoo3
          ports:
            - 2183:2181
          volumes:
            - /home/zk/zoo3/data:/dada
            - /home/zk/zoo3/datalog:/datalog
          environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
            ZOO_AUTOPURGE_PURGEINTERVAL: 1

