server:
  port: 9001

spring:
  application:
    name: seatashop-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://senvmc1a:3306/seata_shop_user?
      serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: APJ@com123
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        ephemeral: false
        namespace: 785fa1c8-0f7a-4cca-9321-4cbc30914af5

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients:
      - seatashop-order

# MyBatisPlus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
  type-aliases-package: org.seatashop.shop.pojo

logging:
  level:
    com:
      seatashop: debug

# eureka client
#eureka:
#  client:
#    service-url:
#      defaultZone: http://seatashop:seatashop123@localhost:8761/eureka/eureka