version: "3.3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:2.0.3
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      - "8861:8848"
      - "9861:9848"
      - "10555:9555"
    env_file:
      - ../env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:2.0.3
    container_name: nacos2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    ports:
      - "8862:8848"
      - "9862:9848"
    env_file:
      - ../env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql

  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:2.0.3
    container_name: nacos3
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
    ports:
      - "8863:8848"
      - "9863:9848"
    env_file:
      - ../env/nacos-hostname.env
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: mysql8
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8801:80"
    volumes:
      - ../nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf/conf.d:/etc/nginx/conf.d
      - ../nginx/log:/var/log/nginx
      - ../nginx/html:/usr/share/nginx/html
    container_name: "nginx"
    depends_on:
      - nacos1
      - nacos2
      - nacos3
